### ISSUE TITLE
Problema com meu spotify após intalação

### ISSUE THREAD

**Issue by ghost** [keowu/spotify-ads-cracker#1]
Fala João, blz? Estava navegando pelo github e resolvi testar esse seu projeto de bloqueador de ads do spotify, mas após a instalação meu spotify nem funciona mais rs. Tem algum jeito de eu desinstalar esse programa pra ele voltar ao normal?

**Comment by keowu** [comment]
Olá, Desconhecido(Conta excluída), tudo certo e com você ? 
Cara não apague sua conta senão o Github move sua issue para spam e eu não recebo a notificação por e-mail, faz um bom tempo que não atualizo mais inclusive obrigado por sua issue vou atualizar essas implementações para o Spotify atual, ao testar obtive sucesso com a versão Web, para desinstalar você precisa:

1 - Acessar o arquivo hosts presente em:
C:\Windows\System32\drivers\etc\hosts
2- Escale privilégios para fazer essa edição(Execute um editor de texto padrão como administrador)
3 - Apague as linhas comentadas da seguinte forma:
#inicio do spotify ads block
Apague o meio
#fim do spotify crack
4 - Reinicie para que o sistema operacional se adeque as novas politicas de rede após isso você não devera mais ter problemas.

Espero ter ajudado, qualquer duvida sinta-se livre para perguntar.
